layout_spectrum: 0.7816189
typography_spectrum: 0.3045028
color:
  lightness: 0.7343223
  brandStrength: 0.7681282
  saturation: 0.5736343
  rhythmicContrast: 0.6318932
  brandColors:
    - '#FBF9FB'
    - '#CF6501'
    - '#B29077'
    - '#040105'
    - '#FFD802'
name: Komatsu Portfolio photography by Tony Ellis
